---
permissions:
- &perm-run-shell-commands
  idstr: "run-shell-commands-perm"
- &perm-get-info
  idstr: "get-info"

roles:
- &admin-role
  id: "admin"
  permissions:
    - *perm-run-shell-commands
    - *perm-get-info

commands:
- &cmd-setup-wireguard
  id: "setup_wireguard"
  cmd: |
    set -e

    name=$(echo $line | awk '{print $1}')
    if [ -z "$name" ]; then
      echo "VPN config name must not be empty"
      exit 1
    fi
    key=$(echo $line | awk '{print $2}')
    if [ -z "$key" ]; then
      echo "VPN config key must not be empty"
      exit 1
    fi
    # infra_cli logs to stderr
    cmd="infra_cli -result-only -use-case vpn -vpn-client-name $name -vpn-pub-key $key"
    set +e
    ip=$($cmd 2>&1)
    set -e
    if [ $? -ne 0 ]; then
      echo "Error occurred while adding your config: $ip"
      exit 1
    fi

    cat << EOF
    Successfully added vpn config for $name!

    Allocated IP address is: $ip

    In your wireguard config, under the [Interface] section, update the "Address" key to "$ip" (without the quotes).
    Example:

    [Interface]
    Address = $ip
    PrivateKey = ...
    
    Once you set this, you should be good to go.
    Feel free to contact me if you are having connectivity issues.

    P.S: You can choose which subnets you want to route through the Wireguard tunnel.
    This can be tweaked in the [Peer] section, under "AllowedIPs" key. "0.0.0.0/0" mean the entire internet.
    If you want to access only my infra services you can set it to "10.0.0.0/8".
    EOF
  prettyName: "Setup Wireguard"
  permissions:
    - *perm-run-shell-commands
  approvedBy: *admin-role
  showCmdOutput: true

- &cmd-setup-openwrt-dns
  id: "setup_openwrt_dns"
  cmd: |
    set -e
    dns=$(echo $line | awk '{print $1}')
    if [ -z "$dns" ]; then
      echo "DNS server must not be empty"
      exit 1
    fi

    set +e
    out=$(infra_cli -use-case setup-openwrt-dns -new-dns "$dns" -result-only 2>&1)
    set -e

    if [ $? -ne 0 ]; then
      echo "Error occurred while updating DNS server on OpenWRT: $out"
      exit 1
    fi

    echo $out

  prettyName: "Setup OpenWRT DNS"
  permissions:
    - *perm-run-shell-commands
  approvedBy: *admin-role
  showCmdOutput: true

- &cmd-setup-email-alias
  id: "setup_email_alias"
  cmd: |
    set -e
    to=$(echo $line | awk '{print $1}')
    if [ -z "$to" ]; then
      echo "Email address to forward emails to must not be empty"
      exit 1
    fi

    set +e
    out=$(infra_cli -use-case add-email-alias -forward-to "$to" -result-only 2>&1)
    set -e

    if [ $? -ne 0 ]; then
      echo "Error occurred while updating adding new email alias: $out"
      exit 1
    fi

    echo "$out. Please wait for a couple of minutes before you start using your new email alias (you can monitor the progress of the job https://drone.viktorbarzin.me/ViktorBarzin/infra/, once this job finishes it can take up to 2 minutes to propagate the changes)"

  prettyName: "Setup Email Alias"
  permissions:
    - *perm-run-shell-commands
  approvedBy: *admin-role
  showCmdOutput: true

groups:
- &viktor-group
  name: "viktor"
  roles:
  - *admin-role

users: 
# - id: "__guest"  # default guest user id
#   name: "Guest user"
- &viktor-fbid 
  id: "3804650372987546" # my fb psid
  # roles: 
  # - *admin-role
  name: "Viktor-fb"
  groups:
    - *viktor-group

---
states:
- id: &state-initial "Initial"
  message: "Let's get started"
- id: &state-hello "Hello"
  message: "How can I help?"
###### Setup state machine ###### 
- id: &state-setup "Setup"
  message: "What are you looking to setup?"
- id: &state-setup-wireguard "SetupWireguard"
  message: |
    I use wireguard as for my VPN. See https://www.wireguard.com/ for more info.

    Steps overview:
    
    1. Install wireguard client from https://www.wireguard.com/install/
    2. Go to: https://wg.viktorbarzin.me and create your config. 
    3. Send me your public key (described later).
    3. Wait for request approval.
    4. Once your request is approved, you will receive a message from me with the IP address you are allocated.

    Let's get you started!
    Please send me your client friendly name and public key in the following format (without the '<>'):    
    <client friendly name> <public key>

    Example:
    Viktor iOcNe48FpLwOa6jBBs9686K5ViPZmLEaJ7axjGT00Xg=
  defaultHandler: *cmd-setup-wireguard
- id: &state-setup-openwrt-dns "SetupOpenWRTDNS"
  message: |
      You can use this command to update OpenWRT's DNS server.

      Please enter the new DNS server's IP address. 
      Recommended values: 
        - 10.0.20.1 (home DNS + PiHole)
        - 1.1.1.1 (Cloudflare's DNS)
        - 9.9.9.9
  defaultHandler: *cmd-setup-openwrt-dns
- id: &state-setup-email-alias "SetupEmailAlias"
  message: |
    You can setup virtual email addresses via my mail infrastructure.
    You will receive a generated random email alias which you can use for whatever you need.
    All emails sent to this random address will be forwarded to the email you provide me now with.
    If you want to check existing aliases go to https://github.com/ViktorBarzin/infra/blob/master/modules/kubernetes/mailserver/extra/aliases.txt).

    A small visualization of how it will work:
    someone -> random-email@viktorbarzin.me -> your_email
    
    Please send me an email address you wish to receive all emails:
  defaultHandler: *cmd-setup-email-alias
###### End of Setup state machine ###### 

###### Info state machine ###### 
- id: &state-info "Info"
  message: "Get more information about my services."
  # permissions:
    # - *perm-get-info
  # Commands are executed in order. If user does not have permission for at least 1, none are executed
  # commands:
  # - *cmd-setup-wireguard
- id: &state-blog "Blog"
  message: "I have a website where I casually blog on various tech topics. To visit my website go to https://viktorbarzin.me"
- id: &state-f1 "F1"
  message: "I have an F1 streaming site, where you can watch F1 streams without annoying pop-ups and ads. \n To watch F1 streams go to http://f1.viktorbarzin.me"
- id: &state-grafana "Grafana"
  message: "I have some pretty dashboards about my infrastructure. Available at https://grafana.viktorbarzin.me/dashboards"
- id: &state-hackmd "Hackmd"
  message: "Document collaboration tool. Similar to Google Docs. Available at https://hackmd.viktorbarzin.me"
- id: &state-privatebin "Privatebin"
  message: "Share pastes securely. Available at https://pb.viktorbarzin.me"
- id: &state-kms "KMS"
  message: "KMS service to license MS Windows and MS Office. Instructions how to use at https://kms.viktorbarzin.me"
- id: &state-mail "Mail"
  message: "Send me an email: me@viktorbarzin.me. Please encrypt your mail using my public PGP key you can get at https://viktorbarzin.me/gpg"
- id: &state-statuspage "StatusPage"
  message: "Check the status of my services at https://status.viktorbarzin.me"
- id: &state-wireguard "Wireguard"
  message: "Check how to get a VPN config at https://wg.viktorbarzin.me"
###### End of Info state machine ###### 

events:
- id: &event-back "Back"
  message: "Back"
  orderID: 95 
- id: &event-getstarted "GetStarted"
  message: "Get Started!"
  orderID: 10 
- id: &event-getinfo "GetInfo"
  message: "Service Info"
  orderID: 10
- id: &event-help "Help"
  message: "Help"
  orderID: 94 
- id: &event-reset "Reset"
  message: "Reset conversation"
  orderID: 99
#### Setup events ####
- id: &event-setup "Setup"
  message: "Setup"
  orderID: 11
- id: &event-setup-wireguard "SetupVPN"
  message: "Setup VPN"
  orderID: 12
- id: &event-setup-openwrt-dns "SetupOpenWRTDNS"
  message: "Setup OpenWRT's DNS"
  orderID: 13
- id: &event-setup-email-alias "SetupEmailAlias"
  message: "Setup Virtual Email"
  orderID: 14
#### End of Setup events ####
#### Info events ####
- id: &event-showbloginfo "ShowBlogInfo"
  message: "Blog info"
  orderID: 11
- id: &event-showf1info "ShowF1Info"
  message: "F1 info"
  orderID: 20
- id: &event-showgrafanainfo "ShowGrafanaInfo"
  message: "Dashboards"
  orderID: 12
- id: &event-showprivatebininfo "ShowPrivatebinInfo"
  message: "Create paste"
  orderID: 13
- id: &event-showhackmdinfo "ShowHackmdInfo"
  message: "Document collab tool"
  orderID: 14
- id: &event-showkmsinfo "ShowKMSInfo"
  message: "KMS service"
  orderID: 15
- id: &event-showmailinfo "ShowMailInfo"
  message: "Mail info"
  orderID: 16
- id: &event-showstatuspagelinfo "ShowStatusPageInfo"
  message: "Status page"
  orderID: 17
- id: &event-showwireguardlinfo "ShowWireguardInfo"
  message: "VPN Config"
  orderID: 18
#### End of Info events ####

statemachine:
- name: *event-getstarted
  src: 
    - *state-initial
  dst: *state-hello
- name: *event-getinfo
  src:
    - *state-hello
  dst: *state-info
# Back to Hello
- name: *event-back
  src:
    - *state-info
  dst: *state-hello
- name: *event-help
  src:
    - *state-info
  dst: *state-info
#### Setup state machine ####
- name: *event-setup
  src: 
    - *state-hello
  dst: *state-setup
- name: *event-back
  src:
    - *state-setup
  dst: *state-hello
- name: *event-setup-wireguard
  src: 
    - *state-setup
  dst: *state-setup-wireguard
- name: *event-setup-openwrt-dns
  src:
    - *state-setup
  dst: *state-setup-openwrt-dns
- name: *event-setup-email-alias
  src:
    - *state-setup
  dst: *state-setup-email-alias
- name: *event-back
  src:
    - *state-setup-wireguard
    - *state-setup-openwrt-dns
    - *state-setup-email-alias
  dst: *state-setup
#### End of Setup state machine ####
#### Info state machine ####
- name: *event-back
  src:
    - *state-blog
    - *state-f1
    - *state-grafana
    - *state-hackmd
    - *state-privatebin
    - *state-kms
    - *state-mail
    - *state-statuspage
    - *state-wireguard
  dst: *state-info
- name: *event-reset
  src:
    - *state-hello
  dst: *state-initial
- name: *event-showbloginfo
  src:
    - *state-info
  dst: *state-blog
- name: *event-showf1info
  src:
    - *state-info
  dst: *state-f1
- name: *event-showgrafanainfo
  src:
    - *state-info
  dst: *state-grafana
- name: *event-showhackmdinfo
  src:
    - *state-info
  dst: *state-hackmd
- name: *event-showprivatebininfo
  src:
    - *state-info
  dst: *state-privatebin
- name: *event-showkmsinfo
  src:
    - *state-info
  dst: *state-kms
- name: *event-showmailinfo
  src:
    - *state-info
  dst: *state-mail
- name: *event-showstatuspagelinfo
  src:
    - *state-info
  dst: *state-statuspage
- name: *event-showwireguardlinfo
  src:
    - *state-info
  dst: *state-wireguard
#### End of Info state machine ####
