---
permissions:
- &perm-run-shell-commands
  idstr: "run-shell-commands-perm"
- &perm-get-info
  idstr: "get-info"

commands:
- &cmd-echo-kek
  id: "echo-kek"
  cmd: "echo kek" 
  prettyName: "echo useful message"
  permissions:
    - *perm-run-shell-commands

roles:
- &admin-role
  id: "admin"
  permissions:
    - *perm-run-shell-commands
    - *perm-get-info

groups:
- &viktor-group
  name: "viktor"
  roles:
  - *admin-role

users: 
# - id: "__guest"  # default guest user id
#   name: "Guest user"
- &viktor-fbid 
  id: "3804650372987546" # my fb psid
  # roles: 
  # - *admin-role
  name: "Viktor-fb"
  groups:
    - *viktor-group

---
states:
- id: &state-initial "Initial"
  message: "Let's get started"
- id: &state-hello "Hello"
  message: "How can I help?"
###### Setup state machine ###### 
- id: &state-setup "Setup"
  message: "What are you looking to setup?"
- id: &state-setup-wireguard "SetupWireguard"
  message: >
    I use wireguard as for my VPN. See https://www.wireguard.com/ for more info.
    

    1. Install wireguard client from https://www.wireguard.com/install/

    2. Go to: https://wg.viktorbarzin.me and create your config (if you don't trust my key generation, feel free to generate your key pair but use the config provided in the sample config)

    3. Wait for approval from admin with further details.

    4. Once your request is approved, you will receive a message from me with the IP address you are allocated.


    Please send me your client friendly name and public key in the following format (without the '<>'):
    
    <client friendly name> <public key>


    Example:

    Viktor iOcNe48FpLwOa6jBBs9686K5ViPZmLEaJ7axjGT00Xg=


    Once your config is setup, I'll will message you to let you know you can start using your config.
  specialstatetype: "vpn"  # for more info see specialstate.go
###### End of Setup state machine ###### 

###### Info state machine ###### 
- id: &state-info "Info"
  message: "Get more information about my services."
  # permissions:
    # - *perm-get-info
  # Commands are executed in order. If user does not have permission for at least 1, none are executed
  # commands:
  # - *cmd-echo-kek
- id: &state-blog "Blog"
  message: "I have a website where I casually blog on various tech topics. To visit my website go to https://viktorbarzin.me"
- id: &state-f1 "F1"
  message: "I have an F1 streaming site, where you can watch F1 streams without annoying pop-ups and ads. \n To watch F1 streams go to http://f1.viktorbarzin.me"
- id: &state-grafana "Grafana"
  message: "I have some pretty dashboards about my infrastructure. Available at https://grafana.viktorbarzin.me/dashboards"
- id: &state-hackmd "Hackmd"
  message: "Document collaboration tool. Similar to Google Docs. Available at https://hackmd.viktorbarzin.me"
- id: &state-privatebin "Privatebin"
  message: "Share pastes securely. Available at https://pb.viktorbarzin.me"
- id: &state-kms "KMS"
  message: "KMS service to license MS Windows and MS Office. Instructions how to use at https://kms.viktorbarzin.me"
- id: &state-mail "Mail"
  message: "Send me an email: me@viktorbarzin.me. Please encrypt your mail using my public PGP key you can get at https://viktorbarzin.me/gpg"
- id: &state-statuspage "StatusPage"
  message: "Check the status of my services at https://status.viktorbarzin.me"
- id: &state-wireguard "Wireguard"
  message: "Check how to get a VPN config at https://wg.viktorbarzin.me"
###### End of Info state machine ###### 

events:
- id: &event-back "Back"
  message: "Back"
  orderID: 95 
- id: &event-getstarted "GetStarted"
  message: "Get Started!"
  orderID: 10 
- id: &event-getinfo "GetInfo"
  message: "Service Info"
  orderID: 10
- id: &event-help "Help"
  message: "Help"
  orderID: 94 
- id: &event-reset "Reset"
  message: "Reset conversation"
  orderID: 99
#### Setup events ####
- id: &event-setup "Setup"
  message: "Setup"
  orderID: 11
- id: &event-setup-wireguard "SetupVPN"
  message: "Setup VPN"
  orderID: 12
#### End of Setup events ####
#### Info events ####
- id: &event-showbloginfo "ShowBlogInfo"
  message: "Blog info"
  orderID: 11
- id: &event-showf1info "ShowF1Info"
  message: "F1 info"
  orderID: 20
- id: &event-showgrafanainfo "ShowGrafanaInfo"
  message: "Dashboards"
  orderID: 12
- id: &event-showprivatebininfo "ShowPrivatebinInfo"
  message: "Create paste"
  orderID: 13
- id: &event-showhackmdinfo "ShowHackmdInfo"
  message: "Document collab tool"
  orderID: 14
- id: &event-showkmsinfo "ShowKMSInfo"
  message: "KMS service"
  orderID: 15
- id: &event-showmailinfo "ShowMailInfo"
  message: "Mail info"
  orderID: 16
- id: &event-showstatuspagelinfo "ShowStatusPageInfo"
  message: "Status page"
  orderID: 17
- id: &event-showwireguardlinfo "ShowWireguardInfo"
  message: "VPN Config"
  orderID: 18
#### End of Info events ####

statemachine:
- name: *event-getstarted
  src: 
    - *state-initial
  dst: *state-hello
- name: *event-getinfo
  src:
    - *state-hello
  dst: *state-info
# Back to Hello
- name: *event-back
  src:
    - *state-info
  dst: *state-hello
- name: *event-help
  src:
    - *state-info
  dst: *state-info
#### Setup state machine ####
- name: *event-setup
  src: 
    - *state-hello
  dst: *state-setup
- name: *event-back
  src:
    - *state-setup
  dst: *state-hello
- name: *event-setup-wireguard
  src: 
    - *state-setup
  dst: *state-setup-wireguard
- name: *event-back
  src:
    - *state-setup-wireguard
  dst: *state-setup
#### End of Setup state machine ####
#### Info state machine ####
- name: *event-back
  src:
    - *state-blog
    - *state-f1
    - *state-grafana
    - *state-hackmd
    - *state-privatebin
    - *state-kms
    - *state-mail
    - *state-statuspage
    - *state-wireguard
  dst: *state-info
- name: *event-reset
  src:
    - *state-hello
  dst: *state-initial
- name: *event-showbloginfo
  src:
    - *state-info
  dst: *state-blog
- name: *event-showf1info
  src:
    - *state-info
  dst: *state-f1
- name: *event-showgrafanainfo
  src:
    - *state-info
  dst: *state-grafana
- name: *event-showhackmdinfo
  src:
    - *state-info
  dst: *state-hackmd
- name: *event-showprivatebininfo
  src:
    - *state-info
  dst: *state-privatebin
- name: *event-showkmsinfo
  src:
    - *state-info
  dst: *state-kms
- name: *event-showmailinfo
  src:
    - *state-info
  dst: *state-mail
- name: *event-showstatuspagelinfo
  src:
    - *state-info
  dst: *state-statuspage
- name: *event-showwireguardlinfo
  src:
    - *state-info
  dst: *state-wireguard
#### End of Info state machine ####
