---
fsm:
- name: "GetStarted"
  srcState: 
    - "Initial"
  destState: "Hello"
- name: "Help"
  srcState:
    - "Hello"
  destState: "Hello"
# Back to Hello state
- name: "Back"
  srcState:
    - "Blog"
    - "F1"
    - "Grafana"
    - "Hackmd"
    - "Privatebin"
    - "KMS"
    - "Mail"
    - "StatusPage"
    - "Wireguard"
  destState: "Hello"
- name: "Reset"
  srcState:
    - "Hello"
  destState: "Initial"
- name: "ShowBlogInfo"
  srcState:
    - "Hello"
  destState: "Blog"
- name: "ShowF1Info"
  srcState:
    - "Hello"
  destState: "F1"
- name: "ShowGrafanaInfo"
  srcState:
    - "Hello"
  destState: "Grafana"
- name: "ShowHackmdInfo"
  srcState:
    - "Hello"
  destState: "Hackmd"
- name: "ShowPrivatebinInfo"
  srcState:
    - "Hello"
  destState: "Privatebin"
- name: "ShowKMSInfo"
  srcState:
    - "Hello"
  destState: "KMS"
- name: "ShowMailInfo"
  srcState:
    - "Hello"
  destState: "Mail"
- name: "ShowStatusPageInfo"
  srcState:
    - "Hello"
  destState: "StatusPage"
- name: "ShowWireguardInfo"
  srcState:
    - "Hello"
  destState: "Wireguard"

          
---
states:
- id: "Initial"
  message: "Let's get started"
- id: "Hello"
  message: "How can I help?"
- id: "Blog"
  message: "I have a website where I casually blog on various tech topics. To visit my website go to https://viktorbarzin.me"
- id: "F1"
  message: "I have an F1 streaming site, where you can watch F1 streams without annoying pop-ups and ads. \n To watch F1 streams go to http://f1.viktorbarzin.me"
- id: "Grafana"
  message: "I have some pretty dashboards about my infrastructure. Available at https://grafana.viktorbarzin.me/dashboards"
- id: "Hackmd"
  message: "Document collaboration tool. Similar to Google Docs. Available at https://hackmd.viktorbarzin.me"
- id: "Privatebin"
  message: "Share pastes securely. Available at https://pb.viktorbarzin.me"
- id: "KMS"
  message: "KMS service to license MS Windows and MS Office. Instructions how to use at https://kms.viktorbarzin.me"
- id: "Mail"
  message: "Send me an email: me@viktorbarzin.me. Please encrypt your mail using my public PGP key you can get at https://viktorbarzin.me/gpg"
- id: "StatusPage"
  message: "Check the status of my services at https://status.viktorbarzin.me"
- id: "Wireguard"
  message: "Check how to get a VPN config at https://wg.viktorbarzin.me"


---
events:
- id: "Back"
  message: "Back"
  orderID: 95 
- id: "GetStarted"
  message: "Get Started!"
  orderID: 10 
- id: "Help"
  message: "Help"
  orderID: 94 
- id: "Reset"
  message: "Reset conversation"
  orderID: 99
- id: "ShowBlogInfo"
  message: "Blog info"
  orderID: 11
- id: "ShowF1Info"
  message: "F1 info"
  orderID: 20
- id: "ShowGrafanaInfo"
  message: "Dashboards"
  orderID: 12
- id: "ShowPrivatebinInfo"
  message: "Create paste"
  orderID: 13
- id: "ShowHackmdInfo"
  message: "Document collab tool"
  orderID: 14
- id: "ShowKMSInfo"
  message: "KMS service"
  orderID: 15
- id: "ShowMailInfo"
  message: "Mail info"
  orderID: 16
- id: "ShowStatusPageInfo"
  message: "Status page"
  orderID: 17
- id: "ShowWireguardInfo"
  message: "VPN Config"
  orderID: 18
